apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: practice2
  labels:
    app: postgres
spec:
  ports:
    - name: http
      port: 5432
      targetPort: http
  selector:
    app: postgres
