apiVersion: v1
kind: Service
metadata:
  name: backend-todo
  namespace: practice2
  labels:
    app: backend-todo
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: backend-todo
